ARG APP_IMAGE
FROM ${APP_IMAGE} AS app-source

FROM nginx:1.27-alpine

# Remove default config and entrypoint scripts that require write access
RUN rm -f /etc/nginx/conf.d/default.conf \
    && rm -rf /docker-entrypoint.d/

# Process template at build time with default value
ENV PHP_FPM_HOST=127.0.0.1
COPY docker/ecs/nginx.conf.template /tmp/nginx.conf.template
RUN envsubst '${PHP_FPM_HOST}' < /tmp/nginx.conf.template > /etc/nginx/conf.d/default.conf \
    && rm /tmp/nginx.conf.template

COPY --from=app-source /var/www/html/public/ /var/www/html/public/

RUN chown -R nginx:nginx /var/cache/nginx /var/run /var/log/nginx /etc/nginx/conf.d

USER nginx

EXPOSE 8080
