worker_processes  2;
worker_rlimit_nofile 3072;

error_log  /var/log/nginx/error.log warn;

# setup custom paths that do not require root access as we execute it as nginx user
pid /tmp/nginx.pid;

events {
  worker_connections 128;
}

http {
    include       mime.types;
    server_tokens off;

    upstream application {
        server 127.0.0.1:9000 fail_timeout=0;
    }

    server {
        listen 8080 default_server;
        server_name _;

        server_tokens off;

        root /var/www/html/public;
        index index.php;

        error_log  /var/log/nginx/error.log warn;
        access_log /var/log/nginx/access.log;

        location /dist/ {
            expires 30d;
            add_header Cache-Control "public, immutable";
            try_files $uri =404;
        }

        location / {
            try_files $uri /index.php$is_args$args;
        }

        location = /healthz {
            access_log off;
            fastcgi_pass application;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root/index.php;
            fastcgi_param REQUEST_URI /index.php/healthz;
            include fastcgi_params;
        }

        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass application;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        location ~ /\. {
            deny all;
        }
    }
}
