<?php

declare(strict_types=1);

namespace SeQura\Demo\Repository;

use SeQura\Core\BusinessLogic\Domain\Connection\Exceptions\InvalidEnvironmentException;
use SeQura\Core\BusinessLogic\Domain\Connection\Models\AuthorizationCredentials;
use SeQura\Core\BusinessLogic\Domain\Connection\Models\ConnectionData;
use SeQura\Core\BusinessLogic\Domain\Connection\RepositoryContracts\ConnectionDataRepositoryInterface;

/**
 * File-backed connection data repository.
 *
 * Reads from an encrypted file generated by the init command.
 * Data is keyed by deployment ID.
 */
final class DemoConnectionDataRepository extends DemoBaseRepository implements ConnectionDataRepositoryInterface
{
    public function __construct()
    {
        parent::__construct('connections.enc');
    }

    /** @inheritDoc */
    public function getConnectionDataByDeploymentId(string $deployment): ?ConnectionData
    {
        $data = $this->getData();

        return isset($data[$deployment]) ? $this->hydrate($data[$deployment]) : null;
    }

    /** @inheritDoc */
    public function setConnectionData(ConnectionData $connectionData): void
    {
        $data = $this->getData();

        $data[$connectionData->getDeployment()] = [
            'environment' => $connectionData->getEnvironment(),
            'merchantId' => $connectionData->getMerchantId(),
            'deployment' => $connectionData->getDeployment(),
            'username' => $connectionData->getAuthorizationCredentials()->getUsername(),
            'password' => $connectionData->getAuthorizationCredentials()->getPassword()
        ];

        $this->setData($data);
    }

    /** @inheritDoc */
    public function getOldestConnectionSettingsStoreId(): ?string
    {
        return 'default';
    }

    /** @inheritDoc */
    public function getAllConnectionSettingsStores(): array
    {
        return ['default'];
    }

    /** @inheritDoc */
    public function getAllConnectionSettings(): array
    {
        return array_map(
            fn(array $item) => $this->hydrate($item),
            $this->getData()
        );
    }

    /** @inheritDoc */
    public function deleteConnectionDataByDeploymentId(string $deploymentId): void
    {
        $data = $this->getData();
        unset($data[$deploymentId]);
        $this->setData($data);
    }

    /**
     * @throws InvalidEnvironmentException
     */
    private function hydrate(array $item): ConnectionData
    {
        return new ConnectionData(
            $item['environment'] ?? '',
            $item['merchantId'] ?? null,
            $item['deployment'] ?? '',
            new AuthorizationCredentials(
                $item['username'] ?? '',
                $item['password'] ?? ''
            )
        );
    }
}
