<?php

declare(strict_types=1);

namespace SeQura\Demo\Repository;

use SeQura\Core\BusinessLogic\Domain\Connection\Models\Credentials;
use SeQura\Core\BusinessLogic\Domain\Connection\RepositoryContracts\CredentialsRepositoryInterface;

/**
 * File-backed credentials repository.
 *
 * Reads from an encrypted file generated by the init command.
 */
final class DemoCredentialsRepository extends DemoBaseRepository implements CredentialsRepositoryInterface
{
    public function __construct()
    {
        parent::__construct('credentials.enc');
    }

    /** @inheritDoc */
    public function setCredentials(array $credentials): void
    {
        $data = $this->getData();

        foreach ($credentials as $credential) {
            $data[] = $credential->toArray();
        }

        $this->setData($data);
    }

    /** @inheritDoc */
    public function getCredentials(): array
    {
        return array_map(
            static fn(array $item) => Credentials::fromArray($item),
            $this->getData()
        );
    }

    /** @inheritDoc */
    public function deleteCredentialsByDeploymentId(string $deploymentId): array
    {
        $removed = [];
        $kept = [];

        foreach ($this->getData() as $item) {
            if (($item['deployment'] ?? '') === $deploymentId) {
                $removed[] = Credentials::fromArray($item);
            } else {
                $kept[] = $item;
            }
        }

        $this->setData($kept);

        return $removed;
    }

    /** @inheritDoc */
    public function getCredentialsByCountryCode(string $countryCode): ?Credentials
    {
        foreach ($this->getData() as $item) {
            if (($item['country'] ?? '') === $countryCode) {
                return Credentials::fromArray($item);
            }
        }

        return null;
    }

    /** @inheritDoc */
    public function getCredentialsByMerchantId(string $merchantId): ?Credentials
    {
        foreach ($this->getData() as $item) {
            if (($item['merchantId'] ?? '') === $merchantId) {
                return Credentials::fromArray($item);
            }
        }

        return null;
    }
}
