<?php

declare(strict_types=1);

namespace SeQura\Demo\Repository;

use SeQura\Core\BusinessLogic\Domain\CountryConfiguration\Models\CountryConfiguration;
use SeQura\Core\BusinessLogic\Domain\CountryConfiguration\RepositoryContracts\CountryConfigurationRepositoryInterface;

/**
 * File-backed country configuration repository.
 *
 * Reads from an encrypted file generated by the init command.
 */
final class DemoCountryConfigRepository extends DemoBaseRepository implements CountryConfigurationRepositoryInterface
{
    public function __construct()
    {
        parent::__construct('countryConfig.enc');
    }

    /** @inheritDoc */
    public function getCountryConfiguration(): ?array
    {
        $data = $this->getData();

        if (empty($data)) {
            return null;
        }

        $configs = [];

        foreach ($data as $item) {
            $code = $item['countryCode'] ?? '';
            $merchantId = $item['merchantId'] ?? '';
            if ($code !== '' && $merchantId !== '') {
                $configs[] = new CountryConfiguration($code, $merchantId);
            }
        }

        return !empty($configs) ? $configs : null;
    }

    /** @inheritDoc */
    public function setCountryConfiguration(array $countryConfigurations): void
    {
        $this->setData(array_map(
            static fn(CountryConfiguration $cc) => [
                'countryCode' => $cc->getCountryCode(),
                'merchantId'  => $cc->getMerchantId(),
            ],
            $countryConfigurations
        ));
    }

    /** @inheritDoc */
    public function deleteCountryConfigurations(): void
    {
        $this->setData([]);
    }
}
