<?php

declare(strict_types=1);

namespace SeQura\Demo\Repository;

use SeQura\Core\BusinessLogic\Domain\Deployments\Models\Deployment;
use SeQura\Core\BusinessLogic\Domain\Deployments\RepositoryContracts\DeploymentsRepositoryInterface;

/**
 * File-backed deployments repository.
 *
 * Reads from an encrypted file generated by the init command.
 */
final class DemoDeploymentsRepository extends DemoBaseRepository implements DeploymentsRepositoryInterface
{
    public function __construct()
    {
        parent::__construct('deployments.enc');
    }

    /** @inheritDoc */
    public function getDeployments(): array
    {
        return array_map(
            static fn(array $item) => Deployment::fromArray($item),
            $this->getData()
        );
    }

    /** @inheritDoc */
    public function getDeploymentById(string $deploymentId): ?Deployment
    {
        foreach ($this->getData() as $item) {
            if (($item['id'] ?? '') === $deploymentId) {
                return Deployment::fromArray($item);
            }
        }

        return null;
    }

    /** @inheritDoc */
    public function setDeployments(array $deployments): void
    {
        $this->setData(array_map(
            static fn(Deployment $d) => $d->toArray(),
            $deployments
        ));
    }

    /** @inheritDoc */
    public function deleteDeployments(): void
    {
        $this->setData([]);
    }
}
